docs/contents.rst, docs/index.rst, docs/middleware/index.rst, polaris/polaris/deposit/views.py, polaris/polaris/helpers.py, polaris/polaris/middleware.py, polaris/polaris/tests/deposit_test.py
Bug fix for #17 
Changes:
- Added PolarisSameSiteMiddleware
- Updated docs
- Added check for correct middleware config in `GET /deposit/webapp`
Updated docs: https://html.jakeurban.now.sh
=> Fix samesite issue

docs/integrations/index.rst, example/server/apps.py, example/server/integrations.py, polaris/polaris/integrations/__init__.py, polaris/polaris/integrations/forms.py, polaris/polaris/integrations/toml.py, polaris/polaris/integrations/transactions.py, polaris/polaris/stellartoml/views.py
=> Defined toml_func integration point, updated docs

docs/integrations/index.rst, polaris/polaris/deposit/urls.py, polaris/polaris/deposit/views.py, polaris/polaris/integrations/transactions.py, polaris/polaris/withdraw/urls.py, polaris/polaris/withdraw/views.py
Adds the integration point needed to allow anchors to use an external application for the interactive flow.
=> Implement external interactive flow integration

polaris/polaris/sep10auth/views.py, polaris/polaris/tests/auth_test.py
#50 
Minor changes to the function to parse the body correctly.
=> Parse url-encoded transaction XDR body correctly

example/server/forms.py, example/server/urls.py, example/server/views.py, polaris/polaris/templates/deposit/form.html, polaris/polaris/templates/withdraw/form.html
=> Reference Server: Added all-fields form and endpoint

example/server/integrations.py, polaris/.env.example, polaris/polaris/sep10auth/views.py, polaris/polaris/settings.py, polaris/polaris/stellartoml/views.py, polaris/polaris/tests/auth_test.py
=> Added independent signing keypair

docs/integrations/index.rst, example/server/apps.py, example/server/integrations.py, polaris/polaris/deposit/views.py, polaris/polaris/integrations/__init__.py, polaris/polaris/integrations/javascript.py, polaris/polaris/templates/base.html, polaris/polaris/transaction/views.py, polaris/polaris/withdraw/views.py
=> Script Integrations

polaris/polaris/management/commands/check_trustlines.py, polaris/polaris/tests/conftest.py, polaris/polaris/tests/deposit_test.py
@yuriescl any comments and suggestions are welcome.
=> Check issuer for in check_trustlines CLI

polaris/polaris/deposit/utils.py, polaris/polaris/settings.py
fixes stellar/django-polaris#128
=> Allow lower-case characters in asset codes

example/server/integrations.py, example/server/urls.py, example/server/views.py
resolves stellar/django-polaris#144
=> Skip Email Confirmation

.circleci/config.yml
resolves stellar/django-polaris#143 
depends on stellar/ops#207
=> Adjusted .config file

docs/index.rst, polaris/polaris/apps.py, polaris/polaris/cors.py
resolves stellar/django-polaris#195
=> Limited all-origin access to Polaris endpoints

example/server/integrations.py, polaris/polaris/integrations/customers.py, polaris/polaris/sep12/customer.py, polaris/polaris/tests/sep12/test_customer.py
resolves stellar/django-polaris#227
=> Added memo and memo_type parameters to SEP-12 DELETE request body

polaris/polaris/tests/processes/test_create_stellar_deposit.py, polaris/polaris/tests/sep24/test_deposit.py, polaris/polaris/utils.py
resolves stellar/django-polaris#255
=> Don't use XDR strings for comparisons

polaris/polaris/sep10/views.py, polaris/polaris/tests/helpers.py
resolves stellar/django-polaris#252
This one is pretty straight forward. The original skeleton code has the functions removed here, I never touched them since they worked. But according to the issue, it actually didn't work all the time.
=> Don't try to manually decode SEP-10 request body

example/server/integrations.py, polaris/polaris/integrations/sep31.py, polaris/polaris/sep31/transactions.py, polaris/polaris/tests/sep31/test_send.py
resolves stellar/django-polaris#262
=> Pass transaction to process_send_request()

docs/contents.rst, docs/index.rst, docs/sep1/index.rst, docs/sep6_and_sep24/index.rst, docs/tutorials/index.rst
resolves stellar/django-polaris#241
=> Add SEP-24 tutorial to Polaris documentation

docs/internationalization/index.rst
update language support on internationalization docs, I have added Bahasa Indonesia.
=> add Bahasa Indonesia to internationalization docs.

example/server/integrations.py, example/server/static/sep24_scripts/add_skip_confirmation_btn.js, example/server/static/sep24_scripts/check_email_confirmation.js, example/server/static/sep24_scripts/google_analytics.js, example/server/static/sep24_scripts/test.js, polaris/polaris/integrations/__init__.py, polaris/polaris/integrations/javascript.py, polaris/polaris/templates/base.html
**WHY**
Makes it simpler for the user to integrate js files, instead of putting js code in a python file
=> change script integration to file names

README.rst, docs/index.rst, example/server/integrations.py, example/server/settings.py, example/server/views.py, polaris/polaris/management/commands/check_trustlines.py, polaris/polaris/management/commands/execute_outgoing_transactions.py, polaris/polaris/management/commands/poll_outgoing_transactions.py, polaris/polaris/management/commands/poll_pending_deposits.py, polaris/polaris/management/commands/watch_transactions.py, polaris/polaris/sep10/views.py, polaris/polaris/sep12/customer.py, polaris/polaris/sep24/deposit.py, polaris/polaris/sep24/utils.py, polaris/polaris/sep24/withdraw.py, polaris/polaris/sep31/info.py, polaris/polaris/sep31/transactions.py, polaris/polaris/sep6/deposit.py, polaris/polaris/sep6/info.py, polaris/polaris/sep6/utils.py, polaris/polaris/sep6/withdraw.py, polaris/polaris/utils.py, polaris/settings.py
resolves stellar/django-polaris#242
=> Standardized polaris logging config

polaris/polaris/management/commands/watch_transactions.py
resolves stellar/django-polaris#275
This refactors `watch_transactions`, no breaking changes. This should make matching transactions more efficient too.
=> Stop iterating through all pending transactions from watch_transactions

example/server/integrations.py, polaris/polaris/integrations/__init__.py, polaris/polaris/integrations/customers.py, polaris/polaris/integrations/javascript.py, polaris/polaris/sep12/customer.py, polaris/polaris/tests/sep12/test_customer.py
resolves stellar/django-polaris#279
In accordance with the recent changes merged to SEP-12.
=> SEP-12: Add 'id' to PUT /customer

example/server/integrations.py, polaris/polaris/integrations/customers.py, polaris/polaris/sep12/customer.py
resolves stellar/django-polaris#304
resolves stellar/django-polaris#303
=> Added 404 response and always pass account to get()

polaris/polaris/admin.py
resolves stellar/django-polaris#307
=> Hide seed when not able to edit asset

polaris/polaris/sep6/deposit.py, polaris/polaris/sep6/withdraw.py
=> SEP-6: pass all request params to process_sep6_request

example/server/integrations.py, polaris/polaris/integrations/sep31.py, polaris/polaris/sep31/info.py, polaris/polaris/tests/sep31/test_info.py
=> SEP-31: updated SEP-31 integration docstring and validation

polaris/polaris/sep6/deposit.py, polaris/polaris/sep6/withdraw.py, polaris/polaris/tests/sep6/test_deposit.py, polaris/polaris/tests/sep6/test_withdraw.py
=> SEP-6: Make min/max amounts optional & overridable

docs/sep6_and_sep24/index.rst, polaris/polaris/integrations/transactions.py, polaris/polaris/sep31/transactions.py, polaris/polaris/sep6/transaction.py, polaris/polaris/sep6/urls.py, polaris/polaris/tests/sep31/test_update.py, polaris/polaris/tests/sep6/test_update.py, polaris/polaris/utils.py
=> SEP-6: PATCH /transactions support

polaris/polaris/shared/serializers.py
resolves #347 
The `decimal.Decimal` class uses exponent notation for numbers smaller than `0.000001` (6 decimals). Stellar only supports 7 decimals of precision, leaving 9 possible values where the Decimal class uses exponent notation, which is corrected here. This is only relevant if 7 digits are needed to represent the anchored Stellar asset.
cc @yuriescl
=> Fixed minor decimal representation issue

polaris/polaris/sep24/utils.py
=> SEP-24: improve interactive jwt token expiration message

polaris/polaris/sep24/info.py, polaris/polaris/tests/sep24/test_info.py
=> SEP-24: remove transaction(s) attributes from /info

polaris/polaris/integrations/transactions.py, polaris/polaris/sep24/deposit.py, polaris/polaris/sep24/withdraw.py, polaris/polaris/tests/sep24/test_deposit.py, polaris/polaris/tests/sep24/test_withdraw.py
=> SEP-24: support delayed KYC approval

polaris/polaris/management/commands/testnet.py, polaris/polaris/tests/commands/test_testnet.py
=> fix sequence number bug for setting home domain

docs/sep12/index.rst, example/server/integrations.py, polaris/polaris/integrations/customers.py, polaris/polaris/sep12/customer.py, polaris/polaris/sep12/urls.py, polaris/polaris/templates/polaris/base.html, polaris/polaris/tests/sep12/test_customer.py
=> SEP-12: Property Verification

polaris/polaris/sep24/withdraw.py
resolves #291 
Thanks @ianeinser for reporting.
=> SEP-24: fix withdraw memo overwrite bug

polaris/polaris/sep10/views.py
=> SEP-10: catch exception for ill-formed POST SEP-10 request body

example/server/integrations.py, polaris/polaris/sep12/customer.py, polaris/polaris/tests/sep12/test_customer.py
resolves #464 
Updates the validation function to comply with the changes made to SEP-12 for property verification.
=> SEP-12: update GET /customer response object format

polaris/polaris/locale/id/LC_MESSAGES/django.po, polaris/polaris/locale/pt/LC_MESSAGES/django.po, polaris/polaris/sep12/customer.py
Hello @ronaldoy @oonid can you update your respective language files for the v1.5 release?
Translations that are no longer used in source code have been removed.
=> Update locale strings for v1.5

polaris/polaris/static/polaris/scripts/callback.js, polaris/polaris/static/polaris/scripts/disableSubmitOnClick.js, polaris/polaris/static/polaris/scripts/dynamicAmountPadding.js, polaris/polaris/static/polaris/scripts/feeTable.js, polaris/polaris/static/polaris/scripts/styleHelpers.js, polaris/polaris/templates/polaris/base.html, polaris/polaris/templates/polaris/more_info.html
=> Removed all JS code from django templates

polaris/polaris/static/polaris/scripts/feeTable.js
resolves #478 
v1.5.1 has been released with the patch included in this PR. These changes ensure the fix will be included in future non-patch releases.
cc @yuriescl
=> SEP-24: fix fee table calculation

polaris/polaris/static/polaris/base.css, polaris/polaris/static/polaris/form-styles/forms.scss, polaris/polaris/templates/polaris/deposit.html, polaris/polaris/templates/polaris/withdraw.html
=> SEP-24: Add asterisk to required fields

polaris/polaris/management/commands/process_pending_deposits.py
Remove a particularly noisy log statement.
=> remove check trustlines initial log statement

example/server/integrations/deposit.py, example/server/integrations/withdraw.py
=> SEP-24: adjust guidance for selecting assets

polaris/polaris/apps.py
=> Increase in-memory precision to match database

polaris/polaris/management/commands/watch_transactions.py, polaris/polaris/models.py
Fixes errors when running `watch_transactions` and `process_pending_deposits` management commands
=> Switch left references of Server to ServerAsync

.circleci/config.yml
This reverts commit d682b9d7675ea61acea47fb56d329df8d5efa005.
=> Revert "print heroku:auth prior to deploying (#627)"

polaris/sep6/withdraw.py, polaris/utils.py
=> SEP-6 bug: use registered `CustodialIntegration` receiving address for withdrawals

polaris/sep12/customer.py, server/integrations/customers.py
Fixes a shallow copy and attribute error in the reference server's customer integration for SEP-12's `GET /customer`.
=> fix shallow copy and attribute error bugs in customers integration

.github/workflows/release.yml
Installs poetry on ubuntu without actions/setup-python@v4
=> Fix poetry installation

polaris/tests/test_utils.py, polaris/utils.py
Cherry-picking #708 onto master
=> add signature to on change callback requests, fix callback body schema
