- README.md
- polaris/polaris/deposit/views.py
- polaris/polaris/fee/views.py
- polaris/polaris/helpers.py
- polaris/polaris/settings.py
- polaris/polaris/templates/error.html
- polaris/polaris/tests/deposit_test.py
- polaris/polaris/tests/fee_test.py
- polaris/polaris/tests/helpers.py
- polaris/polaris/tests/settings.py
- polaris/polaris/tests/transaction_test.py
- polaris/polaris/tests/transactions_more_info_test.py
- polaris/polaris/tests/transactions_test.py
- polaris/polaris/tests/withdraw_test.py
- polaris/polaris/transaction/views.py
- polaris/polaris/withdraw/views.py
- pytest.ini
- setup.py
Reason:
I discovered django rendering issues from hitting Polaris endpoints while testing from stellar-anchor-server.
Problem:
For our `/interactive_deposit`, `/interactive_withdraw`, and `/more_info` endpoints, we were returning an HTML form for a successful request and JSON for a failed request. This was causing django to fail while attempting to render the response.
It turns out that Django Rest Framework doesn't play nicely with returning different content types from the same endpoint, see [the docs](https://www.django-rest-framework.org/api-guide/renderers/). Essentially, the caller of the endpoint must specify the content type they're expecting, otherwise Django Rest Framework expects our endpoints to return the default content type for the function.
Solution:
I converted each of …
> Changed HTML-serving endpoints to only serve HTML

- polaris/polaris/deposit/urls.py
- polaris/polaris/deposit/views.py
- polaris/polaris/tests/deposit_test.py
- polaris/polaris/tests/withdraw_test.py
- polaris/polaris/urls.py
- polaris/polaris/withdraw/urls.py
- polaris/polaris/withdraw/views.py
In stellar/stellar-protocol#438 we change the /deposit and /withdraw endpoints to new URLs and change them to POST instead of GET for security. This makes the changes specified in that PR.
Changes /deposit to /transactions/deposit/interactive
Changes /withdraw to /transactions/withdraw/interactive
Changes both endpoints to POST
Land with stellar/sep24-demo-client#133
> Convert to new POST endpoints

- README.md
- polaris/polaris/deposit/urls.py
- polaris/polaris/deposit/views.py
- polaris/polaris/management/commands/create_stellar_deposit.py
- polaris/polaris/templates/transaction/more_info.html
- polaris/polaris/tests/deposit_test.py
- polaris/polaris/tests/withdraw_test.py
- polaris/polaris/urls.py
- polaris/polaris/withdraw/urls.py
- polaris/polaris/withdraw/views.py
Only one change is included in 0.9.2: https://github.com/stellar/django-polaris/pull/6
I want to review this change again. Here are a few things I'm seeing:
- The SEP-24 protocol documentation and doc strings (less important) aren't up to date. Particularly, `/deposit` and `/withdraw` are no longer listed in the API Endpoints section but they are still referenced throughout the document. This ties into my next point.
- This change moves `/deposit` to `/transactions/deposit/interactive` but also keeps `/deposit/confirm_transaction` and `/deposit/interactive_deposit` where they are
- The SEP and PR appear to communicate that `/deposit` and `/withdraw` were completely removed. I personally feel like we should either move all `/deposit` and `/withdraw` routes under `/transactions`, or none at …
> 0.9.2.dev to master

- polaris/polaris/deposit/urls.py
- polaris/polaris/deposit/views.py
- polaris/polaris/templates/transaction/more_info.html
- polaris/polaris/tests/deposit_test.py
Removed the `/confirm_transaction` endpoint. The client-side call to this endpoint should be removed if it hasn't already been @msfeldstein.
This endpoint can be removed because we added the `poll_pending_deposits` docker container process, which periodically checks for transactions that are ready to be execute on the stellar network (a.k.a. the user has deposited the amount in the anchors account). If a transaction is ready, the same code from `/confirm_transaction` is executed.
Michael, can you confirm the changes to the JavaScript/HTML are good? I removed the "confirm" button and call to `/confirm_transaction`. We don't need the button, but should we replace it with some kind of indicator that the wallet is waiting for the anchor to execute the transaction?
> Removed /confirm_transaction

- docs/integrations/index.rst
- polaris/polaris/integrations/transactions.py
- polaris/polaris/templates/transaction/more_info.html
- polaris/polaris/transaction/views.py
Issue #26 
Changes:
- Added `instructions_for_pending_deposit` to `DepositIntegration`
- Call `instructions_for_pending_deposit` in more_info if transaction is `pending_user_transfer_start`
- Adjust `more_info.html` template to include "Instructions" section when `instructions` is not null
> Deposit Instructions

- README.rst
Make clear in README that this is a django reusable-app, not a standalone application, or a framework, or a library.
The README states that this is an app, but to someone not familiar with django idioms the term is easily misleading. Using a ubiquitous language to talk about what this project is in relation to the Python ecosystem and link to documentation about what type of thing this is will help prevent some misunderstandings.
Specifically this will help preventing someone like myself making the mistake I made.
> Make clear in README that this is a django reusable-app

- polaris/polaris/deposit/views.py
- polaris/polaris/transaction/serializers.py
- polaris/polaris/transaction/views.py
- polaris/polaris/withdraw/views.py
#47 
The `/transactions` endpoint was attempting to generate a single more_info URL for a list of transactions. The changes ensure each transaction in the response has its own more_info URL.
> Fixed /transactions more_info response attribute

- polaris/polaris/helpers.py
Simply removed the check for an existing authenticated session before decoding the JWT.
> New account, same session bug for interactive flow

- docs/integrations/index.rst
- polaris/polaris/deposit/views.py
- polaris/polaris/helpers.py
- polaris/polaris/integrations/transactions.py
- polaris/polaris/templates/deposit/form.html
- polaris/polaris/templates/withdraw/form.html
- polaris/polaris/withdraw/views.py
#78 
Major Changes:
- Renamed `form_for_transaction` to `content_for_transaction`
- This is a better name since we're returning the form _plus_ text content to be rendered in the HTML
- Changed the return type of `content_for_transaction` to a dictionary instead of the tuple
- This is a better design since you can always expect 1 return value, not multiple or `None`
- Support serving pages without forms during the interactive flow
- This would be needed if the user needs to take some action before continuing with the flow, like  confirming their email
> Serve pages with no form in the interactive flow

- example/server/apps.py
- example/server/integrations.py
- polaris/polaris/deposit/views.py
- polaris/polaris/integrations/__init__.py
- polaris/polaris/integrations/javascript.py
- polaris/polaris/transaction/views.py
- polaris/polaris/withdraw/views.py
resolves stellar/django-polaris#134 
Also changes `registered_javascript_func` to `registered_scripts_func` and the `register_integrations()` `javascript_func` parameter to `scripts_func`.
> Pass page_content to registered script func

- example/server/integrations.py
- polaris/polaris/deposit/views.py
- polaris/polaris/helpers.py
- polaris/polaris/integrations/forms.py
- polaris/polaris/integrations/transactions.py
- polaris/polaris/locale/pt/LC_MESSAGES/django.po
- polaris/polaris/withdraw/views.py
resolves stellar/django-polaris#150 
nTokens needs to be able to pass their own parameters to the forms served to users during initialization, and this was not previously possible since Polaris initialized the form with URL or POST arguments.
With this change, `content_for_transaction()`'s `form` key value changes from a `forms.Form` class to a tuple containing the form class as well as a dict containing any keyword arguments the anchor wants to use during initialization.
@ronaldoy for reference
> Allow anchor to pass form parameters for initialization

- polaris/polaris/stellartoml/views.py
The sep24 spec states we need a field called TRANSFER_SERVER_SEP0024 but we have TRANSFER_SERVER_0024, this updates that field name
https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#prerequisites
> Fix new TRANSFER_SERVER_SEP0024 field

- polaris/polaris/deposit/views.py
- polaris/polaris/locale/pt/LC_MESSAGES/django.po
- polaris/polaris/withdraw/views.py
resolves #170 
*not ready to be merged, but ready for review*
Returns 422 when the anchor doesn't return content for the interactive flow response AND the transaction is not in `incomplete` status.
@vitchor Can you send me the translation for the error message added?
> return 422 on extra and unprocessable requests

- polaris/polaris/integrations/forms.py
Currently the keypad in iOS shows small numbers with some special characters. This commit changes to a keypad with large numbers, improving user experience on mobile devices.
> Add numeric keypad for amount field

- docs/integrations/index.rst
- example/server/integrations.py
- polaris/polaris/deposit/views.py
- polaris/polaris/integrations/__init__.py
- polaris/polaris/integrations/fees.py
- polaris/polaris/integrations/javascript.py
- polaris/polaris/integrations/toml.py
- polaris/polaris/integrations/transactions.py
- polaris/polaris/withdraw/views.py
This change is in preparation for #179 , which will allow anchors to prefill their forms with parameters from SEP-9. The intention is to simply the flow for prefilling a form's fields.
**Problem Statement**
Without this change, (as #179 is implemented now), anchors must return a dictionary of initialization arguments from `content_for_transaction()` that will then be passed to the form's constructor by Polaris.
This is not a clean design because this dictionary would now contain two types of data: data that is specific to the anchor's logic (the original purpose of the design), and SEP-9 parameters for pre-filling the form. Anchors would need to separate the two types of data from the original dictionary and call `super().__init__(initial=prefill_data)` in the form's `__init__()` …
> Changed content_for_transaction API

- docs/integrations/index.rst
- polaris/polaris/deposit/views.py
- polaris/polaris/helpers.py
- polaris/polaris/integrations/transactions.py
- polaris/polaris/withdraw/views.py
resolves #164 
Added an integration point for anchors to save the SEP-9 fields passed to the `/interactive` endpoints by wallets. 
The anchors are expected to save this information in a model they've defined. Then, for each form requested during the interactive flow, the anchor should return the necessary fields related to the form also returned.
> SEP-9 Support

- polaris/polaris/sep24/withdraw.py
resolves stellar/django-polaris#204
As described in [SEP-24](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#fields-for-withdraw-transactions), the withdraw_memo shouldn't be returned in the transaction JSON until it is ready to be submitted on the network.
> Create withdraw memo after interactive flow

- polaris/polaris/middleware.py
Our custom middleware was adding the `Secure` flag to session cookie thats created when you login to the admin panel. This PR disables use of that flag when in local mode.
Side note: Do we want to continue using PolarisSameSiteMiddleware? This was a fix for iframes, which we no longer recommend in the SEP.
> Disable secure session cookie when in local mode

- polaris/polaris/integrations/transactions.py
- polaris/polaris/management/commands/watch_transactions.py
- polaris/polaris/sep24/deposit.py
- polaris/polaris/sep24/withdraw.py
- polaris/polaris/sep6/deposit.py
- polaris/polaris/sep6/withdraw.py
- polaris/polaris/tests/processes/test_watch_transactions.py
- polaris/polaris/tests/sep24/test_deposit.py
- polaris/polaris/tests/sep6/test_withdraw.py
- polaris/polaris/utils.py
resolves stellar/django-polaris#196
Before this change, funds sent to an anchor's distribution account had to exactly match the amount specified by the user during the interactive flow. This change removes that requirement and now allows the anchor to decide how to handle differing amounts.
Since transactions submitted to Horizon and `Transaction` DB objects in Polaris can no longer be matched using the amount, `memo` is now the only deterministic way to find a match. 
On both SEP 6 and 24, the `memo` request parameter for `/withdraw` and the `memo` attribute returned by the `/transaction` endpoint have different uses. `memo` sent in the request should be used by the anchor to disambiguate users who use the same stellar account, whereas `memo` returned in the `/transaction` endpoint …
> Allow differing amounts in watch_transactions

- example/server/integrations.py
- polaris/polaris/sep12/customer.py
- polaris/polaris/tests/sep12/test_customer.py
Polaris update for adding the `id` attribute to the GET /customer response.
> Allow 'id' to be returned from GET /customer

- docs/sep31/index.rst
- docs/sep6_and_sep24/index.rst
- example/server/integrations.py
- polaris/polaris/integrations/rails.py
- polaris/polaris/integrations/sep31.py
- polaris/polaris/integrations/transactions.py
- polaris/polaris/management/commands/execute_outgoing_transactions.py
- polaris/polaris/management/commands/poll_outgoing_transactions.py
- polaris/polaris/management/commands/poll_pending_deposits.py
- polaris/polaris/management/commands/watch_transactions.py
- polaris/polaris/templates/withdraw/form.html
- polaris/polaris/tests/conftest.py
- polaris/polaris/tests/processes/test_poll_pending_deposits.py
- polaris/polaris/tests/processes/test_watch_transactions.py
- polaris/polaris/tests/sep31/test_transaction.py
- polaris/polaris/tests/sep6/test_withdraw.py
This PR makes breaking changes to the API provided by Polaris' integration classes and functions
**Rails-related Functions:**
First, I moved `DepositIntegration.poll_pending_deposits` to `RailsIntegration.poll_pending_deposits`. I'm considering renaming this function to `poll_incoming_transactions` to match the newly added process `poll_outgoing_transactions`.
The reason to move this function is simple. Not every deposit into the anchor's external accounts are for SEP-6 or SEP-24. For example, a SEP-31 sending anchor can expect users to send them money so they can forward those funds to a receiver. Polaris does not support being a SEP-31 sending anchor, but it could in the future. The point is that SEP-6 and SEP-24 don't have a monopoly on an anchor's incoming non-stellar transactions, …
> Breaking changes: Rails Integrations

- polaris/polaris/integrations/fees.py
- polaris/polaris/management/commands/execute_outgoing_transactions.py
- polaris/polaris/management/commands/poll_pending_deposits.py
- polaris/polaris/sep24/deposit.py
- polaris/polaris/sep24/withdraw.py
**Fee Calculation and Integration**
This change involves transferring the responsibility of calculating `transaction.amount_fee` from Polaris to the anchor. Currently, Polaris makes the call to the registered fee function whenever the client passes a transaction's `amount`. This is ultimately unneeded and complicates fee calculation when the amount actually sent to the anchor differs from the amount originally specified in a API request.
Instead, we can simply require the anchor to calculate `transaction.amount_fee` whenever funds have been sent to the anchor, and the anchor needs to send funds (either off or on chain) to a user.
Specifically, we can require anchors to assign `transaction.amount_fee` in the following integration functions:
- `poll_pending_deposits` when the user sends …
> Fee integration changes

- README.rst
- docs/index.rst
- example/server/settings.py
- polaris/polaris/settings.py
- polaris/settings.py
resolves stellar/django-polaris#235
Simplifies setup by using an autogenerated settting Django creates. Also adds the optional `ENV_PATH` setting which is a absolute path to the environment file.
> Remove PROJECT_ROOT setting

- docs/sep6_and_sep24/index.rst
- example/server/integrations.py
- polaris/polaris/integrations/forms.py
- polaris/polaris/integrations/javascript.py
- polaris/polaris/integrations/transactions.py
- polaris/polaris/sep24/deposit.py
- polaris/polaris/sep24/withdraw.py
- polaris/polaris/shared/endpoints.py
- polaris/polaris/templates/__init__.py
- polaris/polaris/tests/sep24/test_deposit.py
resolves stellar/django-polaris#233
`content_for_transaction()`, an integration function for both `DepositIntegration` and `WithdrawalIntegration`, is an important piece of Polaris' SEP-24 support. With it, anchors return the form they want to present to the user _and_ additional page content, such as the icon, its label, and guidance for the user.
For example:
_"Stellar Development Foundation"_ is the label string returned from the reference server's `content_for_transaction()` function.
_"Please enter the amount you would like to transfer."_ is also guidance from that function.
This type of content, specifically a page title, icon, and icon label, is also needed in the more info page. But `content_for_transaction()` isn't called when requests for the more info page are made. The …
> Split content_for_transaction() into two functions

- polaris/polaris/management/commands/watch_transactions.py
resolves stellar/django-polaris#254
Polaris has several other processes that perform necessary functions.
When the `watch_transactions` process is down, clients can still make payments to the anchor's distribution account on Stellar. In order to ensure we don't miss a payment, we start stream payment transactions starting at the time of the last successfully processed payment transaction whenever `watch_transactions` is started.
We should include SEP-31 payments in this query for the most recent TX. Currently, its possible to miss transactions if the anchor only supports SEP-31.
> Include SEP-31 transaction in query for last successful TX received

- example/server/integrations.py
- polaris/polaris/integrations/transactions.py
- polaris/polaris/management/commands/watch_transactions.py
- polaris/polaris/sep6/deposit.py
- polaris/polaris/sep6/utils.py
- polaris/polaris/sep6/withdraw.py
- polaris/polaris/tests/sep6/test_deposit.py
- polaris/polaris/tests/sep6/test_withdraw.py
resolves stellar/django-polaris#247
As described in the issue, this change passes the `Transaction` object to `process_sep6_request()`, which allows the developer to link the transaction created as a result of the request to the rest of the anchor's data model.
I'll also be updating SEP-31's `process_send_request()` integration function to pass the `Transaction` object instead of the id to match this solution.
> Pass transaction to process_sep6_request integration functions

- docs/index.rst
- docs/sep1/index.rst
- docs/sep10/index.rst
- docs/sep12/index.rst
- docs/sep31/index.rst
- docs/sep6_and_sep24/index.rst
- example/server/settings.py
- polaris/polaris/sep1/views.py
- polaris/polaris/settings.py
- polaris/polaris/urls.py
- polaris/polaris/utils.py
- polaris/settings.py
resolves stellar/django-polaris#253
The only two variables in `settings.py` Polaris looks for currently are `ENV_PATH` and `ACTIVE_SEPS`. When stellar/django-polaris#248 is implemented, Polaris will look in `settings.py` after checking the environment for the variables expected there. We'll have to update the functionality introduced here once that is merged.
> Prepend Polaris-specific settings with 'POLARIS_'

- README.rst
- example/server/integrations.py
- polaris/polaris/integrations/__init__.py
- polaris/polaris/integrations/javascript.py
- polaris/polaris/management/commands/testnet.py
resolves stellar/django-polaris#266
Adds a Django command so anchors can issue assets mirroring the https://github.com/stellar/create-stellar-token project.
Also adds a `reset` subcommand for reseting the most-recent `paging_token` for each anchored asset and re-issues each asset in the DB. `paging_token` must be reset when testnet resets so Polaris can begin streaming from the network again.
Also includes formatting changes from @acharb 's recent commit on script integrations. Polaris uses the [black](https://pypi.org/project/black/) formatter for its python code.
TODO: update `pending_trust` transactions to `error`
> Testnet CLI command

- docs/index.rst
- polaris/polaris/settings.py
resolves stellar/django-polaris#248
Looks in `django.conf.settings` (settings.py) if no variable with the given name is found in the environment. This allows Polaris users to put all settings in settings.py.
> Use settings.py if variable is not found in environment

- docs/contents.rst
- docs/deployment/index.rst
- docs/sep31/index.rst
- docs/sep6_and_sep24/index.rst
- docs/tutorials/index.rst
Initially taken from stellar/django-polaris#274
The docs could use descriptions of each of the CLI commands.
> Added docs on CLI commands

- docs/internationalization/index.rst
- docs/sep6_and_sep24/index.rst
- docs/tutorials/index.rst
- example/server/settings.py
- polaris/polaris/middleware.py
- polaris/polaris/sep24/utils.py
resolves stellar/django-polaris#294
`PolarisSameSiteMiddleware` was introduced when iframes were the recommended way to open interactive URLs. However, this recommendation has been changed to popups. 
This changes the HTTPS cookie policy required to persist session cookies. Specifically it makes it such that the `SameSite` flag doesn't need to be `None`, which is what `PolarisSameSiteMiddleware` did.
> Remove Polaris middleware requirement

- polaris/polaris/integrations/customers.py
- polaris/polaris/sep12/customer.py
- polaris/polaris/tests/sep12/test_customer.py
resolves stellar/django-polaris#306
Simple but breaking change. Updates the exception to match the other functions for SEP-12.
> Change SEP-12 DELETE exception from ValueError to ObjectDoesNotExist

- polaris/polaris/management/commands/check_trustlines.py
- polaris/polaris/management/commands/execute_outgoing_transactions.py
- polaris/polaris/management/commands/poll_outgoing_transactions.py
- polaris/polaris/management/commands/poll_pending_deposits.py
The management commands need to gracefully exit, otherwise they can be interrupted in the middle of transactions and the database might get inconsistent.
This pull request uses the native `signal` module to register the `SIGINT` and `SIGTERM` signals. When the process is either interrupted by Ctrl+C or killed, it finishes the current loop iteration and then exits.
Without a graceful exit, a common scenario that can cause issues is when the code is being deployed/updated on the server, and all the management commands get killed in order to be restarted to run the new code. This can cause the process to stop at a random point and some transactions might get into an inconsistent state in the database (went through but status wasn't updated, etc).
> exit commands gracefully

- polaris/polaris/sep24/utils.py
- polaris/polaris/tests/sep24/test_deposit.py
resolves stellar/django-polaris#299
This makes the interactive JWT used a one-time token. If included in the URL of an interactive webapp GET request after being authenticated in a prior GET request, the server should reject the token. This ensures only one window can be opened.
> Disallow including the token after previously being authenticated

- polaris/polaris/apps.py
- polaris/polaris/management/commands/poll_pending_deposits.py
- polaris/polaris/migrations/0003_auto_20201009_1300.py
- polaris/polaris/models.py
- polaris/polaris/settings.py
- polaris/polaris/tests/conftest.py
- polaris/polaris/tests/processes/test_create_stellar_deposit.py
- polaris/polaris/tests/processes/test_poll_pending_deposits.py
- polaris/polaris/utils.py
resolves stellar/django-polaris#334
Polaris 1.1.0 changed `Asset` initialization to check for whether or not an in-memory cache record existed for the `Asset`'s distribution account. If no record of the asset existed in the cache, Polaris would do two things:
- Make an API call to Horizon for the asset's distribution account
- Make a DB query to save the account's signers and weights from the Horizon response
This is a bug and 1.1.0 as well as 1.1.1 will likely be removed from PyPi. Version `1.1.2` will be released with this change.
> Replace loading distribution account on startup with on-demand in-memory loading

- polaris/polaris/templates/polaris/more_info.html
When status is `pending_user_transfer_start`, the amount isn't received from the user yet, so it's confusing to have `Amount received` as the label:
`Amount to be received` is more appropriate in that case.
> more_info.html lang improvement

- docs/deployment/index.rst
- polaris/polaris/integrations/rails.py
- polaris/polaris/management/commands/poll_pending_deposits.py
- polaris/polaris/tests/auth_test.py
- polaris/polaris/tests/processes/test_poll_pending_deposits.py
resolves stellar/django-polaris#324
Adds `pending_external` `Transaction` objects to the `poll_pending_deposits()` call. This allows anchors to periodically check on transactions they know are en-route but funds have not been received. Prior, anchors were forced to leave these transactions in `pending_user_transfer_start`, which may have confused the user.
Also fixes a test bug where we check the SEP10 domain using `urllib.parse.urlparse`s `hostname` attribute instead of `netloc`.
> Pass 'pending_external' transaction to poll_pending_deposits()

- docs/deployment/index.rst
- polaris/polaris/management/commands/watch_transactions.py
- polaris/polaris/tests/processes/test_watch_transactions.py
resolves stellar/django-polaris#355
The issue describes the problem better, but basically we need to support matching streamed payments in all forms, not just via payment operations. So I added support for matching path payment ops, both strict send and strict receive.
> Match Path Payments from Clients

- polaris/polaris/integrations/transactions.py
- polaris/polaris/management/commands/poll_pending_deposits.py
- polaris/polaris/tests/sep24/test_deposit.py
- polaris/polaris/utils.py
resolves #361 
- removes `handle_bad_signatures_error()`, Polaris doesn't need to try and recover when multisig transactions don't have the necessary signatures; the developer marked them as ready and they weren't
- Catches 504 errors gracefully and updates the transaction status to `error`
- `submit_stellar_deposit()` now only completes or raises an error
- changes `has_trustline()` to `is_pending_trust()` to make the name reflect the value returned
- Updates comments
> Simplify & improve submit transaction logic

- docs/index.rst
- polaris/polaris/management/commands/poll_pending_deposits.py
- polaris/polaris/management/commands/testnet.py
- polaris/polaris/settings.py
- polaris/polaris/utils.py
resolves #366 
- Adds a `MAX_TRANSACTION_FEE_STROOPS` environment variable
- Updates all instances of building transactions with the updated fee calculation logic
The reason I didn't make changes to resubmit rejected transactions is I learned from [the docs](https://www.stellar.org/developers/horizon/reference/errors/timeout.html) that a transaction is considered for 3 consecutive ledgers before being rejected, so one request is like getting 3 attempts anyway. It is also expensive on a synchronous system to retry requests that can take a long time to return.
> Add transaction fee limit env variable

- polaris/polaris/settings.py
BASE_FEE_MULTIPLIER -> MAX_TRANSACTION_FEE_STROOPS
The transaction fee limit var in the env file was mistakenly labeled as `BASE_FEE_MULTIPLIER` instead of what was documented as `MAX_TRANSACTION_FEE_STROOPS`
> fix bug to pull correct env var from file

- example/server/templates/polaris/more_info.html
- polaris/polaris/shared/endpoints.py
This PR fixes a bug where Polaris rendered deposit instructions on a withdraw transaction's `more_info.html` page. 
Those who use the `DepositIntegration().instructions_for_pending_deposit()` function and do not validate that `transaction.kind == Transaction.KIND.deposit` are affected by this bug.
If the wallet requests a `postMessage` callback and closes the popup when one is received, then this page is never displayed to the user and there is no affect.
> bug fix: don't display deposit instructions on withdraw more info page

- polaris/polaris/shared/endpoints.py
- polaris/polaris/templates/polaris/more_info.html
This PR makes Polaris compliant with SEP-24, which states that only one callback request should be made. Previously, `more_info.html` would make a callback request on every page load, if a `callback` parameter was given.
> SEP-24: only make callback requests to opener once

- docs/tutorials/index.rst
While setting up an anchor POC, I did not realize at first that I needed to use the `migrate.py` shell, I was just using the regular python shell and receiving errors. I think this could help explain that the user needs to perform this specific action to get into the shell with the management context loaded.
> Add an explanatory command to tutorial

- polaris/polaris/templates/polaris/base.html
- polaris/polaris/templates/polaris/deposit.html
- polaris/polaris/templates/polaris/withdraw.html
resolves #406 
Makes the `.amount-input` element's `paddingLeft` attribute depend on the width of `.icon`. This PR also adds a space between the symbol and amount in the fee table.
cc @yuriescl
> SEP-24: make amount input symbol padding variable

- polaris/polaris/templates/polaris/base.html
resolves #402
The fee table now waits until the user has not entered any input for 500 milliseconds before making an API call to the `/fee` endpoint, and will cancel any in-progress call if new input is made. 
cc @yuriescl
> SEP-24: fix fee table updates

- example/server/integrations.py
- polaris/polaris/templates/polaris/more_info.html
This PR changes the `example` application's behavior by calculating `Transaction.amount_fee` and `Transaction.amount_out` as soon as `Transaction.amount_in` is provided by the user.
The one change made to the Polaris library is that the SEP-24 `more_info.html` template will now use the labels `Amount To Be Deposited` and `Amount To Be Withdrawn` if `Transaction.status` is not `completed` AND a value is assigned to `Transaction.amount_out`.
> SEP-6 & 24: save amount_fee and amount_out asap, adjust SEP-24 more_info labels

- polaris/polaris/sep24/info.py
- polaris/polaris/sep31/info.py
- polaris/polaris/sep6/info.py
- polaris/polaris/tests/sep24/test_info.py
resolves #421 
All SEPs implementing an `/info` endpoint (6, 24, 31) define `min_amount` and `max_amount` to be optional, but Polaris always displayed them. This ensures they are only displayed if their values are different from the default values.
> only display /info amount limits if set

- example/server/forms.py
- polaris/polaris/integrations/forms.py
- polaris/polaris/templates/polaris/base.html
partially resolves #427
Updates the JavaScript code in `base.html` to detect a type form attribute using the `id_type` HTML ID and uses it in calls to `GET /fee`. Also updates the reference server to use the functionality and updates `TransactionForm` documentation.
cc @yuriescl
> SEP-24: Detect `TransactionForm.type` attribute and use in `GET /fee` requests

- polaris/polaris/templates/polaris/deposit.html
- polaris/polaris/templates/polaris/withdraw.html
Some Anchors might wanna use form hidden fields to identify which form is being submitted to `form_for_transaction` integration function.
For example, if there are two forms, the user fills the first one and submits it, then gets redirected to the next form, but then presses the browser back button, then submits the first form again, the Anchor can know the user is re-submitting the first form by, for example, looking at the value of a certain hidden field:
```
class WithdrawalForm0(forms.Form):
step = forms.CharField(
widget=forms.HiddenInput(attrs={'value': '0'}),
required=True
)
...
class WithdrawalForm1(forms.Form):
step = forms.CharField(
widget=forms.HiddenInput(attrs={'value': '1'}),
required=True
)
...
```
> SEP-24 added support to form hidden fields

- README.rst
- example/nginx-letsencrypt.conf
Anchors might need a reference configuration for Nginx. It took me some time to get it working properly, specially the HTTPS and proxy.
> Added Nginx example configuration

- polaris/polaris/sep10/views.py
resolves #443 
This change ensures one JWT is provided for a given challenge transaction.
> Use SEP-10 challenge's min time bound for JWT 'iat' value

- docs/index.rst
- example/server/integrations.py
- polaris/polaris/integrations/rails.py
- polaris/polaris/integrations/sep31.py
- polaris/polaris/integrations/transactions.py
- polaris/polaris/management/commands/execute_outgoing_transactions.py
- polaris/polaris/sep24/deposit.py
- polaris/polaris/sep24/withdraw.py
- polaris/polaris/settings.py
- polaris/polaris/templates/polaris/base.html
- polaris/polaris/tests/sep24/test_deposit.py
- polaris/polaris/tests/sep24/test_withdraw.py
resolves #452
Gives SEP-24 anchors who use the built-in interactive flow the ability to add the fee amount to the amount the user should send the anchor, which enables the user to receive the amount specified in the `TransactionForm`.
Note that for SEP-6 and SEP-31, this setting has no effect and anchors must implement this functionality on their own.
cc @yuriescl 
Warning: because client applications could theoretically send an amount that differs from the amount initially specified, Polaris overwrites `Transaction.amount_in` with the amount actually received on Stellar. So anchors who wish to add fees to the amount clients send must ensure `Transaction.amount_fee` is the appropriate amount for `Transaction.amount_in` within `RailsIntegration.execute_outgoing_transaction`. If the fee is …
> SEP-24: allow fees to be additive

- polaris/polaris/apps.py
resolves #453 
I'm keeping the log statement about being in `LOCAL_MODE` as a warning-level log because its the only setting that actually disables some security features, but the SSL-related log statements will be made debug-level.
cc @yuriescl
> Make SSL-related warnings debug-level logs

- polaris/polaris/templates/polaris/more_info.html
resolves #454 
Adjust the labels displayed on the more info page:
- `Kind` --> `Transaction Type`
- `ID` --> `Transaction ID`
- `Amount to be Received`/`Amount Received` --> `Send Amount`/`Amount Sent`
- `Amount to be Deposited`/`Amount Deposited` --> `Receive Amount`/`Amount Received`
- `Amount to be Withdrawn`/`Amount Withdrawn` --> `Receive Amount`/`Amount Received`
- `Status` --> `Transaction Status`
- `Start` --> `Started`
cc @yuriescl @antb123
> SEP-24: adjust more_info.html labels

- polaris/polaris/management/commands/check_trustlines.py
- polaris/polaris/management/commands/poll_pending_deposits.py
- polaris/polaris/sep24/deposit.py
- polaris/polaris/sep24/withdraw.py
- polaris/polaris/sep6/deposit.py
- polaris/polaris/sep6/withdraw.py
- polaris/polaris/tests/commands/test_check_trustlines.py
- polaris/polaris/tests/commands/test_poll_pending_deposits.py
- polaris/polaris/tests/sep24/test_deposit.py
- polaris/polaris/tests/sep6/test_deposit.py
resolves #481 
Previous version of Polaris assumed that the account authenticated via SEP-10 was the destination account for the deposited funds. With the changes made in stellar/stellar-protocol#1041, SEP-24 and SEP-6 should allow the client to authenticate with one account and deposit funds to another.
> Allow source and destination accounts that differ from authenticated account

- polaris/polaris/static/polaris/scripts/feeTable.js
resolves #484
Call the calculation function if there is a value in the input field on function invocation, not just when the field's change event fires.
cc @yuriescl
> SEP-24: calculate the fee table values when amount is prefilled

- polaris/polaris/sep24/info.py
- polaris/polaris/sep6/info.py
- polaris/polaris/tests/sep24/test_info.py
- polaris/polaris/tests/sep6/test_info.py
SEP-6 and 24 were just recently updated to allow anchors to indicate whether they support specific features involved facilitating transactions. This PR updates Polaris to specify support for both features, account creation and claimable balances.
> SEP-6 & 24: Add 'features' object to `GET /info` responses

- example/server/integrations.py
- polaris/polaris/integrations/customers.py
- polaris/polaris/integrations/info.py
- polaris/polaris/integrations/rails.py
- polaris/polaris/integrations/sep31.py
- polaris/polaris/integrations/transactions.py
- polaris/polaris/management/commands/execute_outgoing_transactions.py
- polaris/polaris/management/commands/poll_outgoing_transactions.py
- polaris/polaris/management/commands/process_pending_deposits.py
- polaris/polaris/sep24/deposit.py
- polaris/polaris/sep24/withdraw.py
- polaris/polaris/sep6/utils.py
- polaris/polaris/shared/endpoints.py
- polaris/polaris/tests/sep12/test_customer.py
Polaris' base class integration functions previously had an inconsistent behavior: some functions raised `NotImplementedError` when called and others returned `None`. This PR makes this behavior consistent; raising `NotImpelmentedError` for all unimplemented integration functions. 
It also adjusts the Polaris code that calls these functions to expect the error and handle it appropriately. Integrations that are required to fulfill the request made are not handled and will subsequently cause a 500 error on the server. Integrations that are optional have their exceptions caught and handled.
> raise NotImplementedErrors for base integration functions

- polaris/polaris/management/commands/process_pending_deposits.py
I added a bunch of debug log statements while developing the async functionality in `process_pending_deposits`. Some of these log statements should be upgraded to "info" level.
> updating log statements for process_pending_deposits

- MANIFEST.in
resolves #513 
The packaged version of Polaris 2.0.0 doesn't include the `static/polaris/scripts` directory, which is required for SEP-24 deployments. This requires specifying the directory in MANIFEST.in file which is what determines which static files are included when packaging.
I'll have to remove the 2.0.0 release when we publish 2.0.1.
cc @yuriescl
> include scripts directory in manifest file

- polaris/polaris/management/commands/process_pending_deposits.py
- polaris/polaris/sep31/transactions.py
- polaris/polaris/tests/commands/test_poll_pending_deposits.py
- polaris/polaris/tests/sep31/test_send.py
Polaris calls `SEP31ReceiverIntegration.info()` in `POST /transactions` requests so it can validate that the required transaction fields were passed. Starting in v2, Polaris added `request` arguments to all integration functions, but this argument is not passed to the `.info()` call.
This bug didn't result in failing tests because `.info()`'s function signature had 1 positional argument and 1 optional keyword argument. In 2.0, it was updated to have 2 positional arguments and 1 optional keyword. In both v1 and v2, Polaris called the function like so:
```python
expected_fields = registered_sep31_receiver_integration.info(asset, lang).get(
"fields", {}
)
```
Which did not raise any errors when run and no tests evaluated the types of the parameters passed to the function.
> SEP-31: pass request object to info integration for POST /transactions requests

- polaris/polaris/sep31/transactions.py
SEP-31 requires that `POST /transactions` requests contain a `"fields": {"transaction": {}}` structure, but Polaris can be forgiving if the anchor doesn't require any transaction fields and the wallet sends `"fields": {}`.
Previously, Polaris would have returned 400 if the inner `"transaction"` was not present in the request.
> SEP-31: don't require 'transaction' key in 'fields' passed

- polaris/polaris/sep24/deposit.py
- polaris/polaris/sep24/withdraw.py
- polaris/polaris/tests/sep24/test_deposit.py
- polaris/polaris/tests/sep24/test_withdraw.py
The changes to 2.0 involved adjusting how the SEP-24 form integration functions were called, and the order in which they are called in 2.0+ is incorrect.
Polaris must call `after_form_validation()` to validate the form data posted by the client prior to calling `form_for_transaction()` to fetch the next form to serve. However in Polaris 2.0+ this was not the case. The result is that state tracking logic in `after_form_validation()` wouldn't be executed prior to retrieving the next form, causing the wrong form to be displayed or an unexpected exception to occur.
We'll need to release a patch version for this issue.
> SEP-24: fix form validation and retrieval order

- Pipfile
- Pipfile.lock
- example/Pipfile.lock
- setup.py
Address a high-severity dependabot alert -- `sqlparse` is a sub dependency of Django but we can add it as a direct dependency for our package until django requires the patched version or above.
> add sqlparse as a direct dependency after dependabot alert

- example/server/forms.py
- polaris/polaris/integrations/transactions.py
Removes the '*' character from the form, since a value is always selected.
> SEP-24: make select asset field optional

- example/server/integrations/deposit.py
- example/server/integrations/sep31.py
- example/server/integrations/withdraw.py
- example/server/models.py
- polaris/polaris/models.py
- polaris/polaris/sep38/prices.py
- polaris/polaris/sep38/quote.py
- polaris/polaris/sep38/serializers.py
- polaris/polaris/sep38/utils.py
- polaris/polaris/shared/endpoints.py
- polaris/polaris/tests/sep31/test_send.py
- polaris/polaris/tests/sep31/test_transaction.py
- polaris/polaris/tests/sep38/test_info.py
- polaris/polaris/tests/sep38/test_price.py
- polaris/polaris/tests/sep38/test_prices.py
- polaris/polaris/tests/sep38/test_quote.py
- polaris/polaris/tests/sep6/test_deposit.py
- polaris/polaris/tests/sep6/test_withdraw.py
- polaris/polaris/utils.py
Lots of files but a very simple change:
- Added `asset_identification_format` properties to both `Asset` and `OffChainAsset`
- Replaced usage of `OffChain.asset` and `asset_id_format()` with the new properties
> Add asset identification format property to asset models

- polaris/polaris/sep38/serializers.py
The country codes column is nullable, but the serializer expected a non-null value.
> Fix SEP-38 info bug

- example/server/integrations/deposit.py
- example/server/integrations/sep31.py
- example/server/integrations/withdraw.py
The lasted commit to master failed at the deployment stage because there were bad imports I forgot to remove. This commit removes them.
> reference server: remove bad imports

- polaris/polaris/sep24/deposit.py
- polaris/polaris/sep24/withdraw.py
This change was just pushed in a 2.0.7 release. Reported by Lobstr, Polaris should ignore the SEP-9 parameters passed to SEP-24 `/deposit` and `/withdraw` endpoints if the anchor has not implemented the `.save_sep9_fields()` integration.
> SEP-24: optionally ignore SEP-9 fields passed

- example/Pipfile.lock
- polaris/polaris/management/commands/process_pending_deposits.py
- polaris/polaris/management/commands/testnet.py
- polaris/polaris/sep10/token.py
- polaris/polaris/utils.py
The reference server's requirements file was not updated when we updated Polaris' stellar-sdk version.
> Update reference server's Pipfile.lock after stellar-sdk upgrade

- polaris/polaris/management/commands/watch_transactions.py
Polaris assumes that if a transaction is complete, it has a paging token, which is a fair assumption on mainnet. But on testnet, if the last completed transaction was prior to a testnet reset, it won't. This added condition accounts for that and uses "0" as the streaming cursor in those cases.
> transaction streaming: check paging token value

- polaris/polaris/management/commands/process_pending_deposits.py
- polaris/polaris/tests/commands/test_poll_pending_deposits.py
Saves the transaction envelope before submitting it to Stellar.
Previously, Polaris saved transaction envelopes after receiving a successful response from horizon. However, if transaction submission fails, the envelope submitted would not be saved to the database. This can be a problem if anchors try to re-process a deposit transaction that failed on the first attempt due to timeout errors.
If an anchor's distribution account requires multiple signatures prior submission, the above does not apply.
> Save transaction envelope prior to submission

- polaris/polaris/integrations/toml.py
- polaris/polaris/sep1/views.py
When anchors use an integration function to specify the stellar info file's content, Polaris automatically populates many standardized attributes. However, `QUOTE_SERVER` was not being added to the toml file when appropriate.
> bug: Add QUOTE_SERVER to stellar.toml

- polaris/polaris/static/polaris/form-styles/forms.scss
- polaris/polaris/templates/polaris/deposit.html
- polaris/polaris/templates/polaris/withdraw.html
This allows displaying `field.help_text` below the field input:
> Added support for form field.help_text

- polaris/polaris/static/polaris/form-styles/forms.scss
- polaris/polaris/static/polaris/scripts/dynamicAmountPadding.js
Improve asset symbol appearance inside the amount input.
Current:
Proposed by this pull request:
> SEP-24 asset symbol styling

- Pipfile.lock
Resolves a dependabot report that the `pipenv` package needs to be upgraded.
I ran `pipenv update pipenv-to-requirements`, which is the package that installs `pipenv` as a development requirement.
> upgrade pipenv-to-requirements dev package

- polaris/polaris/static/polaris/base.css
- polaris/polaris/static/polaris/form-styles/forms.scss
Builds on the work @yuriescl did to improve the SEP-24 amount field. Compiles the SCSS files and uses our `$light-gray` color vs the custom color originally set.
> update CSS for SEP-24 interactive flow

- polaris/polaris/integrations/customers.py
- polaris/polaris/sep12/customer.py
- polaris/polaris/tests/sep12/test_customer.py
Currently, Polaris requires the `account` SEP-12 request parameter to match account authenticated via SEP-10. However, the SEP states that the `account` request parameter doesn't need to be specified since it is redundant.
This PR updates the request validation logic to only check for a match between account values if the `account` request parameter is provided.
It also ensures that the `memo` value passed to SEP-12 integration functions is always a string. Currently, Polaris will pass `memo` as an integer if `memo_type` is `id`.
> bug fixes: don't require SEP-12 'account' request parameter and always pass 'memo' as a string

- setup.cfg
Adds the `https://` prefix to Polaris' documentation URLs in the packaging configuration. PyPi requested requests to upload a new release without this prefix.
> update packaging home page

- polaris/polaris/utils.py
The `content_type` keyword argument returned from `render_error_response()` and passed to the `Response()` objects Django uses to render content to the client conflicts with the rendering classes set on all endpoints.
Removing this keyword argument ensures that the content rendered to the client is solely determined by the content negotiation process Django uses automatically.
> remove content_type= kwarg from Response objects

- example/server/settings.py
- polaris/polaris/utils.py
- polaris/settings.py
Updates the log message format to include the logger's name (which by convention is equal to the `__name__` python variable) and the line number of the log statement. This also removes the unnecessary subclass of `LogAdapter`.
An unrelated change updates the `polaris/settings.py` file's `MIDDLEWARE` list to match the reference server's list.
> update logging format

- example/server/settings.py
- polaris/settings.py
Uses line numbers in log statements only when the log messages come from a Polaris logger. Other loggers' names may not correspond directly to the python module executing the log statement.
Also removes comments from both settings files.
> adjust logger format for Polaris modules

- polaris/polaris/sep1/views.py
- polaris/polaris/tests/sep1/test_toml.py
When static `stellar.toml` files are not provided by the developer, Polaris generates the `stellar.toml` file itself, but it has been using an incorrect attribute name for SEP-38's base URI.
> use 'ANCHOR_QUOTE_SERVER' when stellar.toml is generated

- .circleci/config.yml
We moved to k8s for our deployment, so we no longer need CircleCI to deploy to Heroku.
> remove deployment CircleCI job

- polaris/management/commands/watch_transactions.py
- polaris/tests/commands/test_watch_transactions.py
resolves #653 
This PR adds support for parsing fee-bump transactions in our transaction monitoring process, `watch_transactions`. Previously, sending payments to Polaris anchors using fee-bumps would cause the process to crash and the transaction would never be detected.
> support streaming fee-bump transactions

- polaris/sep24/deposit.py
- polaris/tests/sep24/test_deposit.py
We made the `account` parameter optional in SEP-24's `POST /deposit` endpoint since it can default to the authenticated account. This PR updates Polaris with that change.
> SEP-24: make `account` param optional in `POST /deposit`

- polaris/locale/utils.py
- polaris/sep24/deposit.py
- polaris/sep24/info.py
- polaris/sep24/utils.py
- polaris/sep24/withdraw.py
- polaris/sep6/deposit.py
- polaris/sep6/info.py
- polaris/sep6/withdraw.py
- polaris/shared/endpoints.py
- polaris/tests/sep6/test_deposit.py
- polaris/tests/sep6/test_info.py
- polaris/tests/sep6/test_withdraw.py
Updates SEP-6 & SEP-24's support for the `lang` parameter, which was recently updated to default to `en` even when the value passed is not supported, instead of returning 400.
> Update SEP-24 & SEP-6 `lang` support

- polaris/sep24/utils.py
> SEP-24 interactive URL token iat: set grace period to 5 minutes

- polaris/integrations/fees.py
`calculate_fee` has been generating this type hint error:
This PR fixes that error. This is a very minor and optional fix, can be merged in a future release.
> Fixed calculate_fee parameter type hint

- .github/release.yml
Adds a github action for publishing Django Polaris to PyPI on creation of a release. Uses the recommend Trusted Publisher approach for authorization.
> add publish github action

- polaris/tests/test_utils.py
- polaris/utils.py
Adds the signature to transaction callback requests for all SEPs and adds an outer `{"transaction": {...}}` key to the callback body in compliance with the standards.
> add signature to on change callback requests, fix callback body schema

- polaris/tests/test_utils.py
- polaris/utils.py
resolves #710 
Polaris' callbacks contain a signatures generated by signing payloads that include a python dict of the transaction. We should be serializing the dict to json and ensuring the serialized string is used for both the signature payload and request body.
> serialize callback body and use it in signature payload
